---
deployment:
  tasks:
    # Set deployment path - cPanel will automatically replace $HOME with your home directory
    - export DEPLOYPATH=$HOME/public_html/
    # Install dependencies (if package.json exists)
    - npm install --production || true
    # Build static export
    - npm run build || npm run export
    # Copy static export files to public_html
    - /bin/cp -R out/_next $DEPLOYPATH
    - /bin/cp -R "out/public" $DEPLOYPATH 2>/dev/null || true
    - /bin/cp out/index.html $DEPLOYPATH
    - /bin/cp "out/404.html" $DEPLOYPATH 2>/dev/null || true
    # Copy API server file (for separate Node.js app setup)
    - /bin/cp api-server.js $DEPLOYPATH 2>/dev/null || true

